name: gontop_user
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  get_it: 7.2.0
  dio: 4.0.4
  share: 2.0.4
  get_storage: 2.0.3
  animate_do: 2.0.0
  flutter_svg: 0.23.0+1
  cached_network_image: 3.1.0+1
  carousel_slider: ^4.0.0
  shimmer: 2.0.0
  google_fonts: 2.1.0
  flutter_rating_bar: 4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter


#run - - -  flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpg"


flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

